name: Auto Merge Main to Testing Branch

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name 'umavemula12'
          git config --global user.email 'umavemula2005@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrelated-histories
          git push origin testing
